# Generated by Django 3.2.7 on 2021-09-13 21:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.FileField(upload_to='media/contracts/')),
                ('residence_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rented_at', models.DateField()),
                ('closed_at', models.DateField()),
                ('updated_at', models.DateField(verbose_name=datetime.datetime(2021, 9, 13, 18, 15, 39, 58818))),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
