# Generated by Django 3.2.7 on 2021-09-13 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='closed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateField(verbose_name=datetime.datetime(2021, 9, 13, 19, 37, 56, 874983)),
        ),
    ]
