# Generated by Django 3.2.7 on 2021-09-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contract_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
    ]
