# Generated by Django 3.2.7 on 2021-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210913_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='residence_value',
            field=models.IntegerField(),
        ),
    ]
