# Generated by Django 3.2.7 on 2021-09-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contract_residence_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Residence',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='ResidenceImage',
            new_name='RoomImage',
        ),
        migrations.RenameField(
            model_name='roomimage',
            old_name='residence',
            new_name='room',
        ),
    ]
