# Generated by Django 3.2.7 on 2021-09-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210918_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
