# Generated by Django 3.2.7 on 2021-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_roomimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
